# Step 1: Build the React app
FROM node:20-alpine AS build

WORKDIR /app

# Copy dependencies files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the project files and build the app
COPY . .
RUN npm run build

# Step 2: Use NGINX to serve the React build files
FROM nginx:alpine

# Remove default nginx.conf and replace it with the custom one
COPY nginx.conf /etc/nginx/templates/default.conf.template

# Copy the built React files to NGINX's public directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
