services:
  test:
    image: alpine
    command: ["sh", "-c", "env && sleep 3600"]
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_EMAIL_LAMBDA=${VITE_EMAIL_LAMBDA}
      # Adjust this based on your setup
    depends_on:
      - wordpress
      - db
    networks:
      - app-network
    restart: always
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./wordpress_data:/var/www/html
    restart: always
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  wordpress:
  db_data:
  wordpress_data:

networks:
  app-network:
    driver: bridge
