services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_EMAIL_API=${VITE_EMAIL_API}
      # Adjust this based on your setup
    depends_on:
      - wordpress
      - db
      - email-api
    networks:
      - app-network
    restart: always
  email-api:
    build:
      context: ./email-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - app-network
    restart: always
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./wordpress_data:/var/www/html
    restart: always
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  wordpress:
  db_data:
  wordpress_data:

networks:
  app-network:
    driver: bridge
